---
title: "Lab #14 - Subset Selection Methods"
author: "Econ 224"
date: "October 25th, 2018"
---

<!-- knitr global options -->
```{r, include = FALSE}
knitr::opts_chunk$set(comment=NA, fig.width=6, fig.height=6, fig.align = 'center')
```

## Introduction
In this lab you will work through Section 6.5 of ISL and record your code and results in an RMarkdown document.
I have added section headings below to help you organize your results.
You do not have to submit this lab, so you don't have to type up a detailed description of what you've done.
However, I'd suggest that you write down some notes for your own future reference.
These will be helpful on the problem set.
You do not need to follow the code in ISL exactly: feel free to use your preferred coding style. 

You will need the `ISLR` package for the lab, so please install it if you have not done so already.
This lab uses the `Hitters` dataset: in particular, we will try to predict a baseball player's `Salary` in a given year using performance statistics from the preceding year. 
Make sure to read the documentation file for `Hitters` before proceeding.
You will also need to use the function `regsubsets` from the `leaps` library.
Be sure to install `leaps` and read the documentation for `regsubsets` before proceeding.
This lab also uses some "base" R plotting commands, i.e. commands that are not part of `ggplot2`. 
If you prefer to use `ggplot2` you are welcome to do so, but for the particular plots being made here it may be easier to stick with base R.
The command `par(mfrow = c(2, 2))` is used to set up a $2\times 2$ grid of plots for use with base R plotting functions.
You can learn more about graphical parameters by entering `?par` at the R console.

## Best Subset Selection 
Work through section 6.5.1 of ISL and add your code and results below.

*Write your code and solutions here.*

## Forward and Backward Stepwise Selection 
Work through section 6.5.2 of ISL and add your code and results below.
*Write your code and solutions here.*


## Choosing Among Models using the Validation Set Approach and CV
Work through section 6.5.3 of ISL and add your code and results below.
Try to finish up through the bottom of page 252. The material on page 253 is fairly complicated and is optional.
