---
title: "Lab #15 - Ridge and LASSO"
author: "Econ 224"
date: "October 30th, 2018"
---

<!-- knitr global options -->
```{r, include = FALSE}
knitr::opts_chunk$set(comment=NA, fig.width=4, fig.height=4, fig.align = 'center')
```

## Introduction
In this lab you will work through Section 6.6 of ISL and record your code and results in an RMarkdown document.
I have added section headings below to help you organize your results.
You do not have to submit this lab, so you don't have to type up a detailed description of what you've done.
However, I'd suggest that you write down some notes for your own future reference.
These will be helpful on the problem set.
You do not need to follow the code in ISL exactly: feel free to use your preferred coding style. 

You will need the `ISLR` package for the lab, so please install it if you have not done so already.
This lab uses the `Hitters` dataset: in particular, we will try to predict a baseball player's `Salary` in a given year using performance statistics from the preceding year. 
Make sure to read the documentation file for `Hitters` before proceeding.
You will also need to use the package `glmnet` so make sure to install it before proceeding.

## Ridge Regression 
Work through section 6.6.1 of ISL and add your code and results below.

*Write your code and solutions here.*




## The Lasso 
Work through section 6.6.2 of ISL and add your code and results below.

*Write your code and solutions here.*



