---
title: "Lab #13 - Resampling Methods"
author: "Econ 224"
date: "October 23rd, 2018"
---

<!-- knitr global options -->
```{r, include = FALSE}
knitr::opts_chunk$set(comment=NA, fig.width=4.5, fig.height=3.5, fig.align = 'center')
```

## Introduction
In this lab you will work through Section 5.3 of ISL and record your code and results in an RMarkdown document.
I have added section headings below to help you organize your results.
You do not have to submit this lab, so you don't have to type up a detailed description of what you've done.
However, I'd suggest that you write down some notes for your own future reference.
These will be helpful on the problem set.

You do not need to follow the code in ISL exactly: feel free to use your preferred coding style. 
In particular, rather than using the `attach` command suggested by ISL, feel free to instead use `dplyr` or related commands to produce more readable and error-resistant code.
If you choose to do this, you will need to select the rows of a tibble *by position*, i.e.\ by row index.
You can do this using the `slice` function in `dplyr`.

You will need the `ISLR` package for the lab, so please install it if you have not done so already.
Note that this lab uses two different datasets: `Auto` and `Portfolio`.
Both of these are included with `ISLR`.
Make sure to read the documentation for each dataset in the R help files before proceeding.
There are also a few new R functions that you will encounter in this tutorial `poly`, `cv.glm`, and `boot`.
Make sure to read the help files for these functions to make sure that you understand how they work.

## The Validation Set Approach 
Work through section 5.3.1 of ISL and add your code and results below.

*Write your code and solutions here.*

## Leave-One-Out Cross-Validation 
Work through section 5.3.2 of ISL and add your code and results below.

*Write your code and solutions here.*

## k-Fold Cross-Validation 
Work through section 5.3.3 of ISL and add your code and results below.

*Write your code and solutions here.*

# The Bootstrap
Work through section 5.3.4 of ISL and add your code and results below.

## Estimating the Accuracy of a Statistic of Interest
*Write your code and solutions here.*

## Estimating the Accuracy of a Linear Regression Model
